### ISSUE TITLE
Matcher breaks on fields with hyphens in name

### ISSUE THREAD

**Issue by mut3** [stoerr/GrokConstructor#17]
Input logline:

```
This is a test.
```

Working Pattern:

```
%{DATA:My_Message}\.
```

Breaking Pattern:

```
%{DATA:My-Message}\.
```

This was found in the web version

**Comment by stoerr** [comment]
Hm! It is not quite clear what could and should be allowed here - the reference
https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html
is silent on this point. The only related restriction I can see is that the used Oniguruma Regex library just allows word characters (basically alphanumeric and _) as regex names, as I did so far for the pattern names. But also allowing '-' seems certainly sensible. I trust grok allows using a dash, too?

I think I'll allow, somewhat arbitrarily, +-.%\* (and _, as it was) too, until someone gives me a reason to change that.

**Comment by mut3** [comment]
Next time I have a test box sitting idle Ill make sure that grok allows this behavior.

Will report back

preliminary results: I don't actually use '-' in any of my field names for any of my grok patterns, hmmmm

**Comment by mut3** [comment]
Finally got around to testing this.
In logstash version 2.3.2
I tested this with this config:

```
input {
  stdin {
    type => "test-message"
  }
}
filter {
  grok {
          match => { "message" => "%{DATA:My_Message}\." }
  }
}
output {
  stdout {
    codec => rubydebug
  }
}
```

And the input string `hello, world.`

This recreated my above test.

Here are the results, changing the `_` in "My_Message" to different potentially destructive characters.

| Character | Output | Verdict |
| --- | --- | --- |
| `-` | `"My-Message" => "hello, world"` | Safe |
| `*` | `"My" => "hello, world"` | Unsafe |
| `+` | `"My" => "hello, world"` | Unsafe |
| `%` | `"My" => "hello, world"` | Unsafe |
| `.` | `"My.Message" => "hello, world"` | Safe |

However i think that `.` is deprecated in field naming, can't find a reference for that, but I don't think the Logstash guys want `.` in field names

**Comment by stoerr** [comment]
Hm! I find it a little difficult to decide what to do, here. I think since the Oniguruma regex library explicitly specifies that only word characters can be used as regex names (?<name>subexp) it would be wise if people restrict themselves to that for grok field names, too, since these have the same function. Mind you, the regex library joni I use doesn't seem to actually enforce that, too - I'm translating grok expressions to (?<name>...), anyway. 8-)  The library used by logstash doesn't enforce that, too - it is perfectly happy with something like (?<rubb#+-*._&@#!^ish>._) , though not %{DATA:rubb#+-_._&@#!^ish} .
