### ISSUE TITLE
Matching breaks with '@' sign as part of the field name

### ISSUE THREAD

**Issue by dizzydis** [stoerr/GrokConstructor#18]
**Test input:**
`19/Jul/2016:20:43:42 +0000`

**Test Grok String:**
`%{HTTPDATE:@logtimestamp}`

Results:

```
19/Jul/2016:20:43:42 +0000
NOT MATCHED. The longest regex prefix matching the beginning of this line is as follows:
prefix  
after match:    19/Jul/2016:20:43:42 +0000
```

**Remove '@' sign:**
`%{HTTPDATE:logtimestamp}`

**Results after Removing '@' sign:**

```
19/Jul/2016:20:43:42 +0000
MATCHED
logtimestamp    19/Jul/2016:20:43:42·+0000
```

This is functionality that Logstash supports.

**Comment by stoerr** [comment]
Sorry, I don't see how I can sensibly fix this. I translate a construction like %{HTTPDATE:logtimestamp} to the regex (?<logtimestamp>theactualregex) , and here the Library https://github.com/jruby/joni complains about this (though strangely not about time@stamp). The Oniguruma Regular Expressions syntax also says "All characters of the name must be a word character".

So this is a difference to the actual logstash which is probably caused since this is implemented in Scala and logstash in ruby, and is not easy to fix. Compare also #17 .
